import { systemWeights } from 'react-native-typography';
export default {
  disabledOpacity: 0.5,
  roundness: 6,
  colors: {
    background: 'rgb(23, 27, 38)',
    custom_rgb217_63_63: 'rgb(217, 63, 63)',
    custom_rgb255_255_255: 'rgb(255, 255, 255)',
    divider: 'rgba(234, 237, 242, 1)',
    error: 'rgb(189, 29, 50)',
    light: 'rgb(142, 149, 171)',
    lightInverse: 'rgba(255, 255, 255, 0.68)',
    medium: 'rgba(70, 78, 88, 1)',
    mediumInverse: 'rgba(255, 255, 255, 0.87)',
    primary: 'rgb(5, 118, 201)',
    secondary: 'rgb(39, 45, 63)',
    strong: 'rgb(222, 222, 222)',
    strongInverse: 'rgba(255, 255, 255, 1)',
    success: 'rgb(13, 135, 96)',
    surface: 'rgb(31, 36, 51)',
  },
  typography: {
    body1: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 26,
    },
    body2: {
      ...systemWeights.regular,
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 22,
    },
    button: {
      ...systemWeights.bold,
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 16,
    },
    caption: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 16,
    },
    headline1: {
      ...systemWeights.bold,
      fontSize: 60,
      letterSpacing: 0,
      lineHeight: 71,
    },
    headline2: {
      ...systemWeights.bold,
      fontSize: 48,
      letterSpacing: 0,
      lineHeight: 58,
    },
    headline3: {
      ...systemWeights.bold,
      fontSize: 34,
      letterSpacing: 0,
      lineHeight: 40,
    },
    headline4: {
      ...systemWeights.bold,
      fontSize: 24,
      letterSpacing: 0,
      lineHeight: 34,
    },
    headline5: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 0,
      lineHeight: 26,
    },
    headline6: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 24,
    },
    overline: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 2,
      lineHeight: 16,
    },
    subtitle1: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 26,
    },
    subtitle2: {
      ...systemWeights.regular,
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 22,
    },
    custom14: {
      ...systemWeights.regular,
      fontSize: 18,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom15: {
      ...systemWeights.thin,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom16: {
      ...systemWeights.light,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom17: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
  },
};
