import { systemWeights } from 'react-native-typography';
export default {
  disabledOpacity: 0.5,
  roundness: 6,
  colors: {
    background: 'rgba(251, 252, 253, 1)',
    blue_card: 'rgb(240, 255, 255)',
    card_green: 'rgb(229, 251, 246)',
    custom_rgb0_0_0: 'rgb(0, 0, 0)',
    custom_rgb223_255_248: 'rgb(223, 255, 248)',
    custom_rgb233_233_233: 'rgb(230, 230, 230)',
    divider: 'rgba(234, 237, 242, 1)',
    error: 'rgba(255, 69, 100, 1)',
    fafafa: 'rgb(250, 250, 250)',
    green_card_colour: 'rgba(234, 249, 246, 0.58)',
    light: 'rgba(165, 173, 183, 1)',
    lightInverse: 'rgba(255, 255, 255, 0.68)',
    lightInverse: 'rgba(255, 255, 255, 0.68)',
    medium: 'rgb(51, 51, 51)',
    mediumInverse: 'rgba(255, 255, 255, 0.87)',
    primary: 'rgb(80, 227, 194)',
    red_card: 'rgba(255, 239, 242, 0.53)',
    secondary: 'rgba(59, 201, 234, 1)',
    strong: 'rgba(18, 20, 44, 1)',
    strongInverse: 'rgba(255, 255, 255, 1)',
    strongInverse: 'rgba(255, 255, 255, 1)',
    surface: 'rgba(255, 255, 255, 1)',
  },
  typography: {
    body1: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 26,
    },
    body2: {
      ...systemWeights.regular,
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 22,
    },
    button: {
      ...systemWeights.bold,
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 16,
    },
    caption: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 16,
    },
    headline1: {
      ...systemWeights.bold,
      fontSize: 60,
      letterSpacing: 0,
      lineHeight: 71,
    },
    headline2: {
      ...systemWeights.bold,
      fontSize: 48,
      letterSpacing: 0,
      lineHeight: 58,
    },
    headline3: {
      ...systemWeights.bold,
      fontSize: 34,
      letterSpacing: 0,
      lineHeight: 40,
    },
    headline4: {
      ...systemWeights.bold,
      fontSize: 24,
      letterSpacing: 0,
      lineHeight: 34,
    },
    headline5: {
      ...systemWeights.bold,
      fontSize: 20,
      letterSpacing: 0,
      lineHeight: 26,
    },
    headline6: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 24,
    },
    overline: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 2,
      lineHeight: 16,
    },
    subtitle1: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 26,
    },
    subtitle2: {
      ...systemWeights.regular,
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 22,
    },
    custom100: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 12,
    },
    custom101: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 14,
    },
    custom102: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 18,
    },
    custom103: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 12,
    },
    custom104: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom105: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom106: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom107: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 17,
    },
    custom108: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 1,
    },
    custom109: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 12,
    },
    custom110: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom111: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 17,
    },
    custom112: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 17,
    },
    custom113: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 17,
    },
    custom14: {
      ...systemWeights.bold,
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 24,
    },
    custom15: {
      ...systemWeights.bold,
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 24,
    },
    custom16: {
      ...systemWeights.bold,
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 20,
    },
    custom17: {
      ...systemWeights.bold,
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 20,
    },
    custom18: {
      ...systemWeights.bold,
      fontSize: 14,
      letterSpacing: 0,
      lineHeight: 22,
    },
    custom19: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 26,
    },
    custom20: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 26,
    },
    custom21: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 16,
    },
    custom22: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 16,
    },
    custom23: {
      ...systemWeights.bold,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom24: {
      ...systemWeights.bold,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom25: {
      ...systemWeights.bold,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom26: {
      ...systemWeights.light,
      fontSize: 16,
      letterSpacing: 0,
      lineHeight: 26,
    },
    custom27: {
      ...systemWeights.bold,
      fontSize: 12,
      letterSpacing: 2,
      lineHeight: 16,
    },
    custom28: {
      ...systemWeights.bold,
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 16,
    },
    custom29: {
      ...systemWeights.bold,
      fontSize: 12,
      letterSpacing: 2,
      lineHeight: 16,
    },
    custom30: {
      ...systemWeights.semibold,
      fontSize: 12,
      letterSpacing: 2,
      lineHeight: 16,
    },
    custom31: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom32: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 26,
    },
    custom33: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 1,
    },
    custom34: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom35: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 1626,
    },
    custom36: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 1626,
    },
    custom37: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 12,
    },
    custom38: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 12,
    },
    custom39: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 12,
    },
    custom40: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 12,
    },
    custom41: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom42: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom43: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 20,
      lineHeight: 20,
    },
    custom44: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 201,
      lineHeight: 20,
    },
    custom45: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 2,
      lineHeight: 20,
    },
    custom46: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom47: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 20,
    },
    custom48: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom49: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom50: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 30,
    },
    custom51: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 12,
    },
    custom52: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom53: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom54: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 20,
      lineHeight: 20,
    },
    custom55: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom56: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 40,
    },
    custom57: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 12,
    },
    custom58: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 14,
    },
    custom59: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 24,
    },
    custom60: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 100,
    },
    custom61: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 24,
    },
    custom62: {
      fontFamily: 'MontserratBold',
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 24,
    },
    custom63: {
      fontFamily: 'MontserratSemiBold',
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 24,
    },
    custom64: {
      fontFamily: 'MontserratSemiBold',
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 24,
    },
    custom65: {
      fontFamily: 'MontserratSemiBold',
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 12,
    },
    custom66: {
      fontFamily: 'MontserratSemiBold',
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 16,
    },
    custom67: {
      fontFamily: 'MontserratSemiBold',
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 17,
    },
    custom68: {
      fontFamily: 'MontserratSemiBold',
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 16,
    },
    custom69: {
      fontFamily: 'MontserratSemiBold',
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 15,
    },
    custom70: {
      fontFamily: 'MontserratSemiBold',
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 12,
    },
    custom71: {
      fontFamily: 'MontserratSemiBold',
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 16,
    },
    custom72: {
      fontFamily: 'MontserratSemiBold',
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 18,
    },
    custom73: {
      fontFamily: 'MontserratSemiBold',
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 16,
    },
    custom74: {
      fontFamily: 'MontserratSemiBold',
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 18,
    },
    custom75: {
      fontFamily: 'MontserratSemiBold',
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 19,
    },
    custom76: {
      fontFamily: 'MontserratSemiBold',
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 18,
    },
    custom77: {
      ...systemWeights.semibold,
      fontSize: 12,
      letterSpacing: 0,
      lineHeight: 18,
    },
    custom78: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 18,
      lineHeight: 16,
    },
    custom79: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 18,
      lineHeight: 14,
    },
    custom80: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 14,
    },
    custom81: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 14,
    },
    custom82: {
      ...systemWeights.regular,
      fontSize: 16,
      letterSpacing: 1,
      lineHeight: 14,
    },
    custom83: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 14,
    },
    custom84: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 16,
      lineHeight: 14,
    },
    custom85: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 14,
    },
    custom86: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 9,
    },
    custom87: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 1,
    },
    custom88: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 20,
    },
    custom89: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 0,
    },
    custom90: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 1,
    },
    custom91: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 4,
    },
    custom92: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 12,
    },
    custom93: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 16,
    },
    custom94: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 18,
    },
    custom95: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 14,
    },
    custom96: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 14,
    },
    custom97: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 12,
      lineHeight: 14,
    },
    custom98: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 14,
    },
    custom99: {
      ...systemWeights.regular,
      fontSize: 12,
      letterSpacing: 1,
      lineHeight: 9,
    },
  },
};
